name: Hourly Express Check & Telegram Notify

on:
  schedule:
    # Runs every hour at the beginning of the hour (minute 0)
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  check_and_notify:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4 # Use the latest version of checkout action

      - name: Set up Python
        uses: actions/setup-python@v5 # Use the latest version of setup-python action
        with:
          python-version: '3.10' # Specify your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-telegram-bot

      - name: Run express check script
        # Pass secrets as environment variables to the script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python express_checker.py # <-- IMPORTANT: Replace 'your_script_name.py' with the actual filename you saved the Python script as
